#!/bin/bash
case $1 in 
    start)
        echo "Starting Service..."
        ;;
    stop)
        echo "Stopping Service..."
        ;;
    *)
        echo "Usage: $0 [start|stop}"
        exit 1
        ;;
esac
